driver:
  name: vagrant
  customize:
      memory: 2048
  network:
     - ["forwarded_port", {guest: 8065, host: 8065}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      box: bento/centos-7.3
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
  - name: debian-9
    driver:
      box: bento/debian-9.0

suites:
  - name: default
    run_list:
      - recipe[mysql_test::default]
      - recipe[mattermost-cookbook::default]
    attributes:
